# Generated by Django 2.0.4 on 2018-09-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_reply_thread'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Tópico'},
        ),
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default='slug', max_length=120, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
